
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCEED = 'LOGIN_SUCCEED'
export const LOGIN_FAILED= 'LOGIN_FAILED'

export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCEED = 'REGISTER_SUCCEED'
export const REGISTER_FAILED = 'REGISTER_FAILED'

export const BUY_SHARE_REQUEST = 'BUY_SHARE_REQUEST'
export const BUY_SHARE_SUCCEED = 'BUY_SHARE_SUCCEED'
export const BUY_SHARE_FAILED = 'BUY_SHARE_FAILED'
